// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-restaurants.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_restaurants_default = defineTool({
  name: "list_restaurants",
  title: "List restaurants",
  description: "List approved, active restaurants on FoodExpress. Optional city filter and text search on name/cuisine.",
  inputSchema: {
    city: z.string().trim().optional().describe("Filter by city, e.g. 'Mansehra'."),
    search: z.string().trim().optional().describe("Search text matched against name or cuisine."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("restaurants").select("id, name, cuisine_type, city, address, is_active, image_url").eq("approval_status", "approved").eq("is_active", true).limit(limit ?? 20);
    if (city) q = q.ilike("city", city);
    if (search) q = q.or(`name.ilike.%${search}%,cuisine_type.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { restaurants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-restaurant-menu.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_restaurant_menu_default = defineTool2({
  name: "get_restaurant_menu",
  title: "Get restaurant menu",
  description: "Return the available menu items for one restaurant, including any size variants and prices.",
  inputSchema: {
    restaurant_id: z2.string().uuid().describe("Restaurant id from list_restaurants."),
    search: z2.string().trim().optional().describe("Optional text filter on item name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ restaurant_id, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("menu_items").select("id, name, description, price, discount_price, sizes, is_deal, deal_label, image_url, category_id").eq("restaurant_id", restaurant_id).eq("is_available", true).limit(200);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's own orders (RLS enforced). Optional status filter and result limit.",
  inputSchema: {
    status: z3.enum([
      "pending",
      "confirmed",
      "preparing",
      "ready_for_pickup",
      "picked_up",
      "on_the_way",
      "awaiting_confirmation",
      "delivered",
      "cancelled"
    ]).optional().describe("Filter by order status."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("orders").select(
      "id, order_number, status, subtotal, delivery_fee, total, restaurant_id, delivery_address, estimated_delivery_time, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_order_default = defineTool4({
  name: "get_order",
  title: "Get order details",
  description: "Get full details for a single order (RLS enforced \u2014 only the customer, assigned rider, restaurant owner, or admin can read it). Includes items.",
  inputSchema: {
    order_id: z4.string().uuid().describe("Order id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const [{ data: order, error: orderErr }, { data: items, error: itemsErr }] = await Promise.all([
      supabase.from("orders").select(
        "id, order_number, status, subtotal, delivery_fee, total, restaurant_id, customer_id, rider_id, delivery_address, special_instructions, estimated_delivery_time, actual_delivery_time, cancellation_reason, created_at"
      ).eq("id", order_id).maybeSingle(),
      supabase.from("order_items").select("id, item_name, item_price, quantity, subtotal, special_instructions").eq("order_id", order_id)
    ]);
    if (orderErr) return { content: [{ type: "text", text: orderErr.message }], isError: true };
    if (itemsErr) return { content: [{ type: "text", text: itemsErr.message }], isError: true };
    if (!order) {
      return { content: [{ type: "text", text: "Order not found or you do not have access." }], isError: true };
    }
    const payload = { order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/cancel-order.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var cancel_order_default = defineTool5({
  name: "cancel_order",
  title: "Cancel order",
  description: "Cancel an order. Customers can cancel only before it enters preparation; restaurant owners and admins can cancel any time before pickup. Requires a reason.",
  inputSchema: {
    order_id: z5.string().uuid().describe("Order id to cancel."),
    reason: z5.string().trim().min(3).describe("Human-readable cancellation reason.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ order_id, reason }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.rpc("cancel_order", {
      _order_id: order_id,
      _reason: reason
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Order cancelled. Result: ${JSON.stringify(data)}` }],
      structuredContent: { ok: data === true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kbhyflhxyqvkrstoyava";
var mcp_default = defineMcp({
  name: "food-express-mcp",
  title: "FoodExpress",
  version: "0.1.0",
  instructions: "Tools for FoodExpress \u2014 a Pakistani food delivery app. Browse open restaurants, read menus, and manage the signed-in user's own orders. All reads are constrained by the user's role (customer / rider / restaurant owner / admin) and existing row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_restaurants_default, get_restaurant_menu_default, list_my_orders_default, get_order_default, cancel_order_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
